Doco
AI4Bharat/INCLUDE-teams-expt pull request #3
Opened 2021-05-19 04:58 UTC by drmcghee

Added to existing documentation and a scripts directory for the ngrok file/run

2021-05-19 08:35 UTC, ankitbko commented on scripts/ngrok.yml
> +authtoken: YOUR_AUTH_TOKEN
We already have ngrik.template.yml, do we need this as well?

2021-05-19 08:36 UTC, ankitbko commented on src/appsettings.template.json
> +{
Do we need this. The `appsettings.json` as exact same values

2021-05-19 08:38 UTC, ankitbko commented on .gitignore
> +appsettings.json
appsettings can be committed to the code. Its part of .net core project structure

2021-05-19 08:39 UTC, ankitbko requested changes

2021-05-19 08:39 UTC, ankitbko commented on scripts/ngrok.Designer.cs
> +﻿//------------------------------------------------------------------------------
Do we need this file?

2021-05-21 02:39 UTC, deesebast commented
Suggestion:  Can we rename debug.md to something like 'Development guide'.  In the doc, we could have two sections, one each for development and deployment.

2021-05-21 10:47 UTC, ankitbko commented
> Suggestion: Can we rename debug.md to something like 'Development guide'. In the doc, we could have two sections, one each for development and deployment.

Yup

2021-06-19 06:13 UTC, roshni-poddar commented
@drmcghee could you please resolve this?

2021-07-02 15:15 UTC, merged